development:
  database: crud_development
  hostname: 
  port: 5432
  user: postgres
  password: 

test:
  database: crud_test
  hostname: localhost
  port: 5432
  user: postgres
  password:    

production:
  database: crud_production
  hostname: localhost
  port: 5432
  user: postgres
  password:   